# http://www.appveyor.com/docs/appveyor-yml

version: 0.2.2-{build}

# branches to build
branches:
  # whitelist
  only:
    - master

  # blacklist
  except:
    - gh-pages

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Install scripts. (runs after repo cloning)
install:
  - npm install -g grunt-cli
  - npm install

# Build the plugin and then link it for testing examples
build_script:
  - grunt
  - npm link
  
# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - ps: "cd ./example"
  - ps: "npm link grunt-hogan"
  - ps: "grunt"
